# Generated by Django 3.1.7 on 2021-05-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_auto_20210324_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorClone',
        ),
    ]
